<?xml version="1.0" encoding="UTF-8"?>
<interface xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Filesystem\Exception\ExceptionInterface" namespace="Symfony\Component\Filesystem\Exception" name="ExceptionInterface" abstract="false" final="false" start="19" end="21">
  <file path="//var/www/html/vendor/symfony/filesystem/Exception" file="ExceptionInterface.php" realpath="/var/www/html/vendor/symfony/filesystem/Exception/ExceptionInterface.php" size="464" time="2022-04-01T12:33:59+00:00" unixtime="1648816439" sha1="1b359041bab737e91a7f2a9c2c7fde022a44f26f" relative="ar/www/html/vendor/symfony/filesystem/Exception/ExceptionInterface.php"/>
  <docblock>
    <description compact="Exception interface for all exceptions thrown by the component."/>
    <author value="Romain Neutron &lt;imprec@gmail.com&gt;"/>
  </docblock>
  <extends full="Throwable" namespace="" name="Throwable"/>
  <parent full="Throwable" namespace="" name="Throwable">
    <method name="getMessage" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the message"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getCode" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the exception code"/>
      <return type="int"/>
    </docblock>
  </method>
    <method name="getFile" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the file in which the exception was created"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getLine" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the line on which the object was instantiated"/>
      <return type="int"/>
    </docblock>
  </method>
    <method name="getTrace" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the stack trace"/>
      <return type="array"/>
    </docblock>
  </method>
    <method name="getTraceAsString" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the stack trace as a string"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getPrevious" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Returns the previous Throwable"/>
      <return type="Throwable"/>
    </docblock>
  </method>
    <method name="__toString" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets a string representation of the thrown object"/>
      <return type="string"/>
    </docblock>
  </method>
  </parent>
  <extenders>
    <extender full="Symfony\Component\Filesystem\Exception\IOExceptionInterface" namespace="Symfony\Component\Filesystem\Exception" name="IOExceptionInterface"/>
  </extenders>
  <implementors>
    <class full="Symfony\Component\Filesystem\Exception\InvalidArgumentException" namespace="Symfony\Component\Filesystem\Exception" name="InvalidArgumentException"/>
    <class full="Symfony\Component\Filesystem\Exception\RuntimeException" namespace="Symfony\Component\Filesystem\Exception" name="RuntimeException"/>
  </implementors>
</interface>
