<?xml version="1.0" encoding="UTF-8"?>
<interface xmlns="http://xml.phpdox.net/src" full="Symfony\Contracts\HttpClient\Exception\HttpExceptionInterface" namespace="Symfony\Contracts\HttpClient\Exception" name="HttpExceptionInterface" abstract="false" final="false" start="21" end="24">
  <file path="//var/www/html/vendor/symfony/http-client-contracts/Exception" file="HttpExceptionInterface.php" realpath="/var/www/html/vendor/symfony/http-client-contracts/Exception/HttpExceptionInterface.php" size="568" time="2022-03-13T20:07:29+00:00" unixtime="1647202049" sha1="71ccfe066d4fb39797c87eef1930769214203ae4" relative="ar/www/html/vendor/symfony/http-client-contracts/Exception/HttpExceptionInterface.php"/>
  <docblock>
    <description compact="Base interface for HTTP-related exceptions."/>
    <author value="Anton Chernikov &lt;anton_ch1989@mail.ru&gt;"/>
  </docblock>
  <extends full="Symfony\Contracts\HttpClient\Exception\ExceptionInterface" namespace="Symfony\Contracts\HttpClient\Exception" name="ExceptionInterface"/>
  <method name="getResponse" start="23" end="23" abstract="false" final="false" static="false" visibility="public">
    <return type="object" nullable="false">
      <type full="Symfony\Contracts\HttpClient\ResponseInterface" namespace="Symfony\Contracts\HttpClient" name="ResponseInterface"/>
    </return>
  </method>
  <extenders>
    <extender full="Symfony\Contracts\HttpClient\Exception\RedirectionExceptionInterface" namespace="Symfony\Contracts\HttpClient\Exception" name="RedirectionExceptionInterface"/>
    <extender full="Symfony\Contracts\HttpClient\Exception\ClientExceptionInterface" namespace="Symfony\Contracts\HttpClient\Exception" name="ClientExceptionInterface"/>
    <extender full="Symfony\Contracts\HttpClient\Exception\ServerExceptionInterface" namespace="Symfony\Contracts\HttpClient\Exception" name="ServerExceptionInterface"/>
  </extenders>
  <parent full="Symfony\Contracts\HttpClient\Exception\ExceptionInterface" namespace="Symfony\Contracts\HttpClient\Exception" name="ExceptionInterface">
    <extends full="Throwable" namespace="" name="Throwable"/>
  </parent>
  <parent full="Throwable" namespace="" name="Throwable">
    <method name="getMessage" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the message"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getCode" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the exception code"/>
      <return type="int"/>
    </docblock>
  </method>
    <method name="getFile" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the file in which the exception was created"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getLine" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the line on which the object was instantiated"/>
      <return type="int"/>
    </docblock>
  </method>
    <method name="getTrace" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the stack trace"/>
      <return type="array"/>
    </docblock>
  </method>
    <method name="getTraceAsString" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the stack trace as a string"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getPrevious" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Returns the previous Throwable"/>
      <return type="Throwable"/>
    </docblock>
  </method>
    <method name="__toString" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets a string representation of the thrown object"/>
      <return type="string"/>
    </docblock>
  </method>
  </parent>
</interface>
