<?xml version="1.0" encoding="UTF-8"?>
<interface xmlns="http://xml.phpdox.net/src" full="Symfony\Contracts\HttpClient\Exception\RedirectionExceptionInterface" namespace="Symfony\Contracts\HttpClient\Exception" name="RedirectionExceptionInterface" abstract="false" final="false" start="19" end="21">
  <file path="//var/www/html/vendor/symfony/http-client-contracts/Exception" file="RedirectionExceptionInterface.php" realpath="/var/www/html/vendor/symfony/http-client-contracts/Exception/RedirectionExceptionInterface.php" size="501" time="2022-03-13T20:07:29+00:00" unixtime="1647202049" sha1="f22469f9bb825475837e6c6741ea73265542d6e8" relative="ar/www/html/vendor/symfony/http-client-contracts/Exception/RedirectionExceptionInterface.php"/>
  <docblock>
    <description compact="When a 3xx response is returned and the &quot;max_redirects&quot; option has been reached."/>
    <author value="Nicolas Grekas &lt;p@tchwork.com&gt;"/>
  </docblock>
  <extends full="Symfony\Contracts\HttpClient\Exception\HttpExceptionInterface" namespace="Symfony\Contracts\HttpClient\Exception" name="HttpExceptionInterface"/>
  <parent full="Symfony\Contracts\HttpClient\Exception\HttpExceptionInterface" namespace="Symfony\Contracts\HttpClient\Exception" name="HttpExceptionInterface">
    <extends full="Symfony\Contracts\HttpClient\Exception\ExceptionInterface" namespace="Symfony\Contracts\HttpClient\Exception" name="ExceptionInterface"/>
    <method name="getResponse" start="23" end="23" abstract="false" final="false" static="false" visibility="public">
      <return type="object" nullable="false">
        <type full="Symfony\Contracts\HttpClient\ResponseInterface" namespace="Symfony\Contracts\HttpClient" name="ResponseInterface"/>
      </return>
    </method>
  </parent>
  <parent full="Symfony\Contracts\HttpClient\Exception\ExceptionInterface" namespace="Symfony\Contracts\HttpClient\Exception" name="ExceptionInterface">
    <extends full="Throwable" namespace="" name="Throwable"/>
  </parent>
  <parent full="Throwable" namespace="" name="Throwable">
    <method name="getMessage" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the message"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getCode" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the exception code"/>
      <return type="int"/>
    </docblock>
  </method>
    <method name="getFile" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the file in which the exception was created"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getLine" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the line on which the object was instantiated"/>
      <return type="int"/>
    </docblock>
  </method>
    <method name="getTrace" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the stack trace"/>
      <return type="array"/>
    </docblock>
  </method>
    <method name="getTraceAsString" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets the stack trace as a string"/>
      <return type="string"/>
    </docblock>
  </method>
    <method name="getPrevious" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Returns the previous Throwable"/>
      <return type="Throwable"/>
    </docblock>
  </method>
    <method name="__toString" abstract="false" static="false" visibility="public" final="false">
    <docblock>
      <description compact="Gets a string representation of the thrown object"/>
      <return type="string"/>
    </docblock>
  </method>
  </parent>
  <implementors>
    <class full="Symfony\Component\HttpClient\Exception\RedirectionException" namespace="Symfony\Component\HttpClient\Exception" name="RedirectionException"/>
  </implementors>
</interface>
